### ISSUE TITLE
Example Notebook

### ISSUE THREAD

**Issue by adityabantwal** [sash-a/hrl_pybullet_envs#2]
Can you please provide a Google Colab notebook showcasing a basic example.

**Comment by sash-a** [comment]
Hi thanks for you interest, this repo is still being actively developed and env specs are changing relatively frequently so if you're intending to use this please do note that. However a notebook is a good idea, I'll whip one up when I have some time.

For now though you can simply create any of the envs using gym: `gym.make("AntGatherBulletEnv-v0")` or `gym.make("AntMazeBulletEnv-v0")`.

I am planning to clean up the code soon and add any push and fall.

**Comment by adityabantwal** [comment]
Also I am unable to render anything it shows a gray screen. I have some more issues can I send an email.

**Comment by sash-a** [comment]
I'm not too sure what your code is so I can't really help you with the grey screen, but if you're trying to render on collab that will be quite tricky. Run it locally if you want to visualize the envs. 

Here's the [collab example](https://colab.research.google.com/drive/17FX7UM1-DDb3oxg1ei64dw9Xa6JFE_zF?usp=sharing) you wanted, no visualization, but if you run it locally and uncomment the `env.render()` line I'm sure you'll be able to see the envs

Feel free to open other issues for any issues you are having or pull request if you want to contribute :+1:

**Comment by sash-a** [comment]
You can also have a look at the example in the readme, I would recommend pasting that into a plain python file and running locally if you are having any problems with rendering

**Comment by nikhilrayaprolu** [comment]
Hey, the visualization of the AntMaze is not showing the complete grid on rendering. Any idea on how to change that?

**Comment by sash-a** [comment]
Not sure what you mean by complete grid, but you can zoom in and out and pan around in pybullets GUI. Use the scroll wheel to zoom and ctrl + left click + move your mouse to rotate around the agent
